version: '3.8'


services:
  db:
    image: postgres:15
    container_name: db
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_DB=postgres
    volumes:
      - db_data:/var/lib/postgresql/data

  odoo:
    image: odoo
    container_name: odoo
    ports:
      - "8069:8069"
    depends_on:
      - db
    environment:
      - HOST=db
    links:
      - db:db
  
volumes:
  db_data: